### ISSUE TITLE
[Docs] gRPC-Spring-Boot-Starter Documentation: Getting Started - Project Setup (Server and Client) Exhibitory Imagery

### ISSUE THREAD

**Issue by arnoldmashava** [grpc-ecosystem/grpc-spring#1077]
¿Where is the exhibitory imagery pertaining to the [Project Setup](https://github.com/grpc-ecosystem/grpc-spring/blob/master/docs/en/server/getting-started.md#project-setup) for the `grpc-spring-server` and [Project Setup](https://github.com/grpc-ecosystem/grpc-spring/blob/master/docs/en/client/getting-started.md#project-setup) for the `grpc-spring-client` components in the `Ver. 3.x Release` iteration of the [Documentation](https://grpc-ecosystem.github.io/grpc-spring/en/)?

I was initially tempted to submit a `Pull Request` but that would have been a untidy *Dirty-Dance*, which without an admissible and valid source URL from which this imagery would be embedded, would translate to completely removing the intended visualizations on how the `gRPC-Spring-Boot-Starter` project should be setup.

Respectively, for the `grpc-spring-server` and `grpc-spring-client` components, the intended [Documentation](https://grpc-ecosystem.github.io/grpc-spring/en/) visualizations point to the following invalid sources:

1. https://grpc-ecosystem.github.io/grpc-spring-boot-starter/assets/images/server-project-setup.svg

2. https://grpc-ecosystem.github.io/grpc-spring-boot-starter/assets/images/client-project-setup.svg

Muchas Gracias.

**Comment by ST-DDT** [comment]
The correct links are:

- https://grpc-ecosystem.github.io/grpc-spring/assets/images/server-project-setup.svg
- https://grpc-ecosystem.github.io/grpc-spring/assets/images/client-project-setup.svg

**Comment by ST-DDT** [comment]
Thanks for bringing this to our attention and your quick fix.

**Comment by arnoldmashava** [comment]
> Thanks for bringing this to our attention and your quick fix.

It is such immense honor @ST-DDT - albeit the seemingly infinitesimal gravitas of my *Dirty-Dancing* moves, in the form of single-line and minor `git commits`.

The anticipation for my *Wandering Eye* is that of enhanced visual stimulus emanating from refined [gRPC-Spring-Boot-Starter Documentation](https://grpc-ecosystem.github.io/grpc-spring/) aesthetics - for the rendered outputs of both the [English](https://grpc-ecosystem.github.io/grpc-spring/en) and [中文](https://grpc-ecosystem.github.io/grpc-spring/zh-CN) `*.md` sets of source files into which the proposed amendments were petrissaged.

Herewith some Orange haze and `Protobuf` levitation:  

```python
>_ sudo ¡Muchas Gracias! --verbose
```
