### ISSUE TITLE
Security scans findings

### ISSUE THREAD

**Issue by dranzey-hub** [grpc-ecosystem/grpc-spring#1101]
**Blackduck source scans findings**

On my company, while scanning our project we found a lot of vulnerabilities coming from this dependency using Blackduck source scan, some dating back to 2005 or older. At first we thought this was probably a false positive from blackduck but contacting them they told us they also see the problems.

**The question**

Is this correct? We are using the latest version released just a couple of weeks ago, doesn't make sense.

**Stacktraces and logs**

For instance, one of your direct dependencies is spring-cloud-starter-netflix-eureka-client 4.1.0, which looking at [maven central](https://mvnrepository.com/artifact/org.springframework.cloud/spring-cloud-starter-netflix-eureka-client/4.1.0) it brings [eureka-client](https://mvnrepository.com/artifact/com.netflix.eureka/eureka-client) 2.0.1 which in turns has [commons-configuration](https://mvnrepository.com/artifact/commons-configuration/commons-configuration)
1.10 as a dependency, this one is very old (Oct 24, 2013) and one of its many vulnerabilities is log4shell coming from log4j 1.2.8

![image](https://github.com/grpc-ecosystem/grpc-spring/assets/76430570/b85d2e95-e7f6-40ee-b5fd-c9697af7989e)

**Comment by ST-DDT** [comment]
The dependency is marked as optional runtime dependency.

````xml
<dependency>
      <groupId>org.springframework.cloud</groupId>
      <artifactId>spring-cloud-starter-netflix-eureka-client</artifactId>
      <version>4.1.0</version>
      <scope>runtime</scope>
      <exclusions>...</exclusions>
      <optional>true</optional>
</dependency>
````

So unless you add them yourself it won't show up in the final application.

Unfortunately, there isn't a patched version of the eureka client lib available, that uses a newer version of that library, so there isn't much we can do here.
Could you please report this to the eureka client lib, so they can fix that?

**Comment by dranzey-hub** [comment]
Thanks for the response.

We will exclude all of those optional dependencies and scan again. I'll let you know the results.

**Comment by dranzey-hub** [comment]
Thanks, there seemed to be problems on the Blackduck scan that were fixed and now the optional dependencies do not show up so we are good.
