### ISSUE TITLE
Metric grpc_server_processing_duration_seconds_max is always 0

### ISSUE THREAD

**Issue by rick-alp** [grpc-ecosystem/grpc-spring#1108]
**The context**

What do you wish to achieve?

**The bug**

grpc_server_processing_duration_seconds_max is always 0 no matter what the call with version 3.0.0.RELEASE,
grpc_server_processing_duration_seconds_sum and grpc_server_processing_duration_seconds_count are okay.

**Steps to Reproduce**

Enable metrics, make a grpc call grpc_server_processing_duration_seconds_max should not be 0

Which versions do you use?
* Spring (boot): 3.2.3
* grpc-spring-boot-starter: 3.0.0.RELEASE
* java: version + architecture (64bit?) 21, 64bit

**Additional context**

* Did it ever work before? Yes, 2.14.0.RELEASE

**Comment by ST-DDT** [comment]
Ref:

- https://github.com/micrometer-metrics/micrometer/issues/5062
