### ISSUE TITLE
@GrpcClient is null spring boot 3

### ISSUE THREAD

**Issue by pdkproitf** [grpc-ecosystem/grpc-spring#1119]
**The context**
I'm implementing a gRPC client using 'net.devh:grpc-client-spring-boot-starter:3.0.0.RELEASE'.
However, I encountered an error: @GrpcClient is null. 
I saw some similar issues reported, but they were using an older version, and the workaround solution links are no longer available, so I'm unable to find the solution

**The bug**

Code:
```
@Service
public class GrpcClientService {
	@GrpcClient("greeting-grpc-server")
	public GreetServiceGrpc.GreetServiceBlockingStub greetServiceStub;

	public String sendMessage(String name) {
		GreetRequest greetRequest = GreetRequest.newBuilder().setName(name).build();
		GreetResponse greetResponse = this.greetServiceStub.greet(greetRequest);
		return greetResponse.getGreeting();
	}
}

```

applicaiton.yml
```
grpc:
  client:
    greeting-grpc-server:
      address: "static://localhost:9090"
      enableKeepAlive: true
      keepAliveWithoutCalls: true
```

Exception:
```
Caused by: java.lang.NullPointerException: Cannot invoke "spring_boot.grpc.GreetServiceGrpc$GreetServiceBlockingStub.greet(spring_boot.grpc.GreetRequest)" because "this.greetServiceStub" is null
```

**The application's environment**

Which versions do you use?
* Spring (boot): 3.2.4
* grpc-java: 
* grpc-client-spring-boot-starter:3.1.0.RELEASE
* java: version + architecture (64bit?): jdk17-64
* Other relevant libraries...

**Additional context**

* Did it ever work before?
* Do you have a demo?

**Comment by pdkproitf** [comment]
I tried this solution, but many server classes are not available.
![Screenshot_2024-06-03_at_22_37_16](https://github.com/grpc-ecosystem/grpc-spring/assets/12691828/f1420ab7-4900-4ac8-aee6-e83327c2e0ac)

**Comment by pdkproitf** [comment]
I tried this solution but it still doesn't work.

![Screenshot 2024-06-03 at 22 42 03](https://github.com/grpc-ecosystem/grpc-spring/assets/12691828/bf4231bb-2b66-44d3-a620-9d021f60cf64)

**Comment by ST-DDT** [comment]
Do you invoke the constructor of GrpcClientService somewhere or do you let Spring handle that?

**Comment by ST-DDT** [comment]
> GrpcClientService grpcClientService = new GrpcClientService();

That line is the issue. Since you create the bean yourself, spring cannot inject anything into it. 

You habe to use `appContext.getBean(GrpcClientService.class)` instead.

**Comment by pdkproitf** [comment]
I see, it works for me. (Spring Boot is still new to me)
Thank you so much @ST-DDT

**Comment by kayodegigz** [comment]
Hi @ST-DDT, I have the same issue. However, I did not manually initialize the bean like they did and let spring handle it. Is there  another solution or it is compulsory to do it their way?

**Comment by ST-DDT** [comment]
That is unusual. Does the error appear during app startup or later while it is running?
If it is during startup maybe the field is used before it is populated.

You might want to debug into

https://github.com/grpc-ecosystem/grpc-spring/blob/b83afe68cef63edc7dfeec694bc279956bbc8c3d/grpc-client-spring-boot-starter/src/main/java/net/devh/boot/grpc/client/inject/GrpcClientBeanPostProcessor.java#L121

To check why the bean/field is ignored.
