### ISSUE TITLE
Transfer the repository to grpc-ecosystem/grpc-spring

### ISSUE THREAD

**Issue by mattdkerr** [grpc-ecosystem/grpc-spring#164]
This repo has the same artifact name, which leads to confusion as to which one you are using in your build. https://github.com/LogNet/grpc-spring-boot-starter
This is unfortunate because it doesn't offer as many features as this one. (Perhaps it's also time to ask if we can migrate this from a personal project area to one of the main Spring ones?)

**Comment by yidongnan** [comment]
If Spring needs an official gRPC project with spring boot, I am happy to migrate this to Spring :smile
At the same time, I did not find a way to submit application.

**Comment by ST-DDT** [comment]
> This repo has the same artifact name, which leads to confusion as to which one you are using in your build. https://github.com/LogNet/grpc-spring-boot-starter
> This is unfortunate because it doesn't offer as many features as this one. 

IIRC there are two different philosophies behind both repositories. This one contains more features and thus is bigger and more complex. The other library wants to remain as small as possible.

> (Perhaps it's also time to ask if we can migrate this from a personal project area to one of the main Spring ones?)

I have no experience with this process. Getting the official "spring" stamp might be helpful for the google search result ranking, but I'm unsure on the implications. @mattdkerr do you know any details regarding that process?

**Comment by ST-DDT** [comment]
It looks like there is a spring issue to provide gRPC support: https://github.com/spring-projects/spring-framework/issues/20905

**Comment by ST-DDT** [comment]
We probably need some external/Spring help for this.

**Comment by mattdkerr** [comment]
Sorry, I don't know how this works, but I think we have a contact at Pivotal. I'll see if I can get a pointer next week.

**Comment by mattdkerr** [comment]
> It looks like there is a spring issue to provide gRPC support: [spring-projects/spring-framework#20905](https://github.com/spring-projects/spring-framework/issues/20905)

added my 2cents to this thread

**Comment by yidongnan** [comment]
After discussions, we have decided to migrate the repository to https://github.com/grpc-ecosystem/grpc-spring, and Google's team will also be actively involved in its development. This project will eventually become the official project for supporting gRPC with Spring.

We appreciate your support and interest in the project.
