### ISSUE TITLE
Are there any plans to add support for SB 3.X?

### ISSUE THREAD

**Issue by Frendzel** [grpc-ecosystem/grpc-spring#953]
Hi guys, as in topic I wanted to ask if you were thinking about it as very soon SB 2.X will have EOL
https://endoflife.date/spring-boot

**Comment by FyiurAmron** [comment]
tl;dr duplicate, since Spring Boot 3.x requires Spring 6.x:

https://github.com/yidongnan/grpc-spring-boot-starter/issues/778

https://github.com/yidongnan/grpc-spring-boot-starter/issues/826

**Comment by dswiecki** [comment]
is there a chance for a Release Candidate version in the near future?

**Comment by dswiecki** [comment]
@FyiurAmron 2.15 is missing #970 where SocketUtils are copied, without this 2.15.0 is unusable with SB 3.x cc @fengli79

**Comment by FyiurAmron** [comment]
@dswiecki true, good point.

**Comment by dswiecki** [comment]
@FyiurAmron @fengli79 @yidongnan Hi, is there a change for a RC or bugfix version in the near future ?

**Comment by fengli79** [comment]
Notice that spring boot 3.0 is going to eol in a few weeks as well (for OSS). https://endoflife.date/spring-boot.
I'd like to understand what's the gap here, besides #970, does the community need more features to be compatible with spring boot 3.0 and 3.1? Consider the timeline of eol, can we go straightforward to 3.1 (any concern from existing users)?

**Comment by Praveen-7163** [comment]
Any ETA for this fix to rolled out?

**Comment by ST-DDT** [comment]
IMO we should merge the autoconfigure projects into the starter projects in order to avoid the empty dependency packages.

**Comment by yidongnan** [comment]
Versions above 3.0.0 support Spring Boot 3.x
