### ISSUE TITLE
CallOptions.withStreamTracerFactory api

### ISSUE THREAD

**Issue by 313hemant313** [grpc-ecosystem/grpc-spring#954]
Wanted to use below grpc-java api's to trace network issues / retry logging.

```
CallOptions.withStreamTracerFactory(ClientStreamTracer.Factory factory)
ClientStreamTracer.inboundTrailers(Metadata trailers)
StreamTracer.streamClosed(Status status)
```

How i can use these with spring grpc ?

**Comment by ST-DDT** [comment]
The same way as in plain grpc java.
Although you could use a configurer bean to set the options globally.
- https://yidongnan.github.io/grpc-spring-boot-starter/en/client/configuration.html#grpcchannelconfigurer
- https://yidongnan.github.io/grpc-spring-boot-starter/en/client/configuration.html#stubtransformer

Please don't ping me if you posted the issues just a few hours ago.

**Comment by 313hemant313** [comment]
@ST-DDT Sorry accidentally tagged you here... wanted to tag on https://github.com/yidongnan/grpc-spring-boot-starter/issues/951

Thanks for your reply.

**Comment by 313hemant313** [comment]
Not able to find **withStreamTracerFactory** in both the options GrpcChannelConfigurer or StubTransformer.

Tried this but not sure if this will replace any existing ClientStreamTracker or not.

    @Bean
    public StubTransformer customStubTransformer() {
        return (name, stub) -> stub.withOption(CallOptions.Key.create("streamTracerFactories"), List.of(new ClientStreamTracer.Factory() {
            @Override
            public ClientStreamTracer newClientStreamTracer(ClientStreamTracer.StreamInfo info, Metadata headers) {
                return new CustomClientStreamTracer(info);
            }
        }));
    }

**Comment by 313hemant313** [comment]
@ST-DDT Grpc-java suggested to use newStub(channel, callOptions)  https://github.com/grpc/grpc-java/issues/2143,

How to go about it in grpc-spring-boot-starter ?

**Comment by ST-DDT** [comment]
> Grpc-java suggested to use newStub(channel, callOptions) [grpc/grpc-java#2143](https://github.com/grpc/grpc-java/issues/2143),

You can replace the stub with a stub transformer or provide a custom stub factory.

But it was also mentioned that you could use an interceptor to set it. Which I would recommend.

**Comment by 313hemant313** [comment]
Not sure how to attach Tracer with interceptor.

This is how we create stub.
`AbstractStub<S> modifiedStub = stub.withInterceptors(MetadataUtils.newAttachHeadersInterceptor(metadata));`

This is the client tracer that i need to attach.
```
public class CustomClientStreamTracer extends ClientStreamTracer {

    private final ClientStreamTracer.StreamInfo streamInfo;

    public CustomClientStreamTracer(ClientStreamTracer.StreamInfo streamInfo) {
        this.streamInfo = streamInfo;
    }

    @Override
    public void streamClosed(Status status) {
        if (status != Status.OK) {
            log.warn("For gRPC streamClosed with status: {}, isTransparentRetry: {} and previousAttempts: {}", status,
                    streamInfo.isTransparentRetry(), streamInfo.getPreviousAttempts());
        }
        super.streamClosed(status);
    }
}
```

@ST-DDT please guide.

**Comment by ST-DDT** [comment]
Somewhat like this:

````java
@GrpcGlobalClientInterceptor
class MyInterceptor implements ClientInterceptor {

    @Override
    public <ReqT, RespT> ClientCall<ReqT, RespT> interceptCall(MethodDescriptor<ReqT, RespT> method, CallOptions callOptions, Channel next) {
   
      return next.newCall(method, callOptions.withStreamTracerFactory(tracerFactory));
  }

}
````
