### ISSUE TITLE
Documentation off-line

### ISSUE THREAD

**Issue by tonyals** [grpc-ecosystem/grpc-spring#980]
**The context**

Hi,
After migration of repository the doc is off-line if we follow this link: https://yidongnan.github.io/grpc-spring-boot-starter/
I think that is part of migration process, if yes I can close this issue :)

**The bug**

404 error when access https://yidongnan.github.io/grpc-spring-boot-starter/

**Stacktrace and logs**

![image](https://github.com/grpc-ecosystem/grpc-spring/assets/43297863/b926eb9a-6996-4ff9-8ba5-62373d9c9c31)

**Steps to Reproduce**

1. Go to https://yidongnan.github.io/grpc-spring-boot-starter/

**Comment by yidongnan** [comment]
I will proceed to set up the redirection. After the redirection is in place, accessing https://yidongnan.github.io/grpc-spring-boot-starter/ will automatically redirect you to https://grpc-ecosystem.github.io/grpc-spring/.

Thank you for bringing this to our attention, and please let me know if you have any further questions or concerns.

**Comment by tonyals** [comment]
Redirection working fine now, thank you very much!
