### ISSUE TITLE
Add userAgent property to GrpcChannelProperties

### ISSUE THREAD

**Issue by onyn** [grpc-ecosystem/grpc-spring#998]
`ManagedChannelBuilder` have userAgent property, which `GrpcChannelProperties` lacks. This data is useful for metrics by client. 

Currently I use workaround:

```java
    @Bean
    GrpcChannelConfigurer configurer(@Value("${spring.application.name}") String appName) {
        return (builder, name) -> {
            builder.userAgent(appName);
        };
    }
```

**Comment by ST-DDT** [comment]
Sounds useful. Would you like to create a PR for this?
